const constants ={
    SIGNUP_REQUEST : "SIGNUP_REQUEST",                      //signup / add user
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_ERROR : "SIGNUP_ERROR",
    LOGIN_REQUEST : "LOGIN_REQUEST",                        //login 
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERROR : "LOGIN_ERROR",
    LIST_POLL_REQUEST : "LIST_POLL_REQUEST",                 //take poll
    LIST_POLL_SUCCESS : "LIST_POLL_SUCCESS",
    LIST_POLL_ERROR : "LIST_POLL_ERROR",
    TAKE_POLL_REQUEST : "TAKE_POLL_REQUEST",                //take poll
    TAKE_POLL_SUCCESS : "TAKE_POLL_SUCCESS",
    TAKE_POLL_ERROR : "TAKE_POLL_ERROR",
    LOG_OUT : "LOG_OUT",
    ADD_POLL_REQUEST : "ADD_POLL_REQUEST",                   //add poll 
    ADD_POLL_SUCCESS : "ADD_POLL_SUCCESS",
    ADD_POLL_ERROR : "ADD_POLL_ERROR",
    DELETE_POLL_REQUEST : "DELETE_POLL_REQUEST",              //delete poll
    DELETE_POLL_SUCCESS : "DELETE_POLL_SUCCESS",
    DELETE_POLL_ERROR : "DELETE_POLL_ERROR",
    DELETE_POLL_OPTION_REQUEST : "DELETE_POLL_OPTION_REQUEST",  //delete poll option
    DELETE_POLL_OPTION_SUCCESS : "DELETE_POLL_OPTION_SUCCESS ",
    DELETE_POLL_OPTION_ERROR : "DELETE_POLL_OPTION_ERROR",
    ADD_POLL_OPTION_REQUEST : "ADD_POLL_OPTION_REQEST",     //add option to poll
    ADD_POLL_OPTION_SUCCESS : "ADD_POLL_OPTION_SUCCESS",
    ADD_POLL_OPTION_ERROR : "ADD_POLL_OPTION_ERROR", 
    EDIT_POLL_TITLE_REQUEST : "EDIT_POLL_TITLE_REQUEST",    //edit poll title
    EDIT_POLL_TITLE_SUCCESS : "EDIT_POLL_TITLE_SUCCESS",
    EDIT_POLL_TITLE_ERROR : "EDIT_POLL_TITLE_ERROR",
    LIST_USERS_REQUEST : "LIST_USERS_REQUEST",              //list all users
    LIST_USERS_SUCCESS : "LIST_USERS_SUCCESS",
    LIST_USERS_ERROR : "LIST_USERS_ERROR",
 }

export default constants;