const constants ={
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_ERROR : "SIGNUP_ERROR",
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERROR : "LOGIN_ERROR",
    LIST_POLL_REQUEST : "LIST_POLL_REQUEST",
    LIST_POLL_SUCCESS : "LIST_POLL_SUCCESS",
    LIST_POLL_ERROR : "LIST_POLL_ERROR",
    TAKE_POLL_REQUEST : "TAKE_POLL_REQUEST",
    TAKE_POLL_SUCCESS : "TAKE_POLL_SUCCESS",
    TAKE_POLL_ERROR : "TAKE_POLL_ERROR",
    LOG_OUT : "LOG_OUT",
 }

export default constants;